export const Options = [
  { id: 1, value: 'porcoes' },
  { id: 2, value: 'bebidas' },
  { id: 3, value: 'lanches' },
  { id: 4, value: 'sobremesas' },
  { id: 5, value: 'pratos principais' },
  { id: 6, value: 'saladas' },
  { id: 7, value: 'sopas' },
  { id: 8, value: 'sanduíches' },
  { id: 9, value: 'massas' },
  { id: 10, value: 'vegetariano' },
  { id: 11, value: 'vegano' },
  { id: 12, value: 'carnes' },
  { id: 13, value: 'frutos do mar' },
  { id: 14, value: 'acompanhamentos' },
  { id: 15, value: 'cafés' },
  { id: 16, value: 'chás' },
  { id: 17, value: 'sucos' },
  { id: 18, value: 'sorvetes' },
  { id: 19, value: 'vinhos' },
  { id: 20, value: 'cervejas' },
  { id: 21, value: 'drinks e coquetéis' },
  { id: 22, value: 'petiscos' },
  { id: 23, value: 'pizzas' },
  { id: 24, value: 'especiais da casa' },
  { id: 25, value: 'risotos' },
  { id: 26, value: 'aves' },
  { id: 27, value: 'peixes' },
  { id: 28, value: 'queijos e frios' },
  { id: 29, value: 'orgânicos' },
  { id: 30, value: 'sem glúten' },
  { id: 31, value: 'sem lactose' },
  { id: 32, value: 'light e diet' },
  { id: 33, value: 'wraps e burritos' },
  { id: 34, value: 'comida oriental' },
  { id: 35, value: 'comida mexicana' },
  { id: 36, value: 'comida brasileira' },
  { id: 37, value: 'comida italiana' },
  { id: 38, value: 'tapas e antepastos' },
  { id: 39, value: 'grãos e cereais' },
  { id: 40, value: 'panquecas e waffles' },
  { id: 41, value: 'omeletes e quiches' },
  { id: 42, value: 'crepes e tapiocas' },
];
